const wordList = [
    { word: "johnwick", hint: "The nick name of one of the CS teacher" },
    { word: "apple", hint: "Fruit" },
    { word: "eiffel", hint: "Paris" },
    { word: "tiger", hint: "Predator" },
    { word: "python", hint: "Language" },
    { word: "jupiter", hint: "Planet" },
    { word: "mountain", hint: "Peak" },
    { word: "chocolate", hint: "Sweet" },
    { word: "hamburger", hint: "Sandwich" },
    { word: "lighthouse", hint: "Beacon" },
    { word: "bicycle", hint: "Wheels" },
    { word: "volcano", hint: "Eruption" },
    { word: "giraffe", hint: "Tall" },
    { word: "robot", hint: "Machine" },
    { word: "octopus", hint: "Tentacles" },
    { word: "sushi", hint: "Japanese" },
    { word: "pyramid", hint: "Ancient" },
    { word: "keyboard", hint: "Typing" },
    { word: "pirate", hint: "Outlaw" },
    { word: "unicorn", hint: "Mythical" },
    { word: "chameleon", hint: "Lizard" },
    { word: "castle", hint: "Fortress" },
    { word: "dinosaur", hint: "Prehistoric" },
    { word: "rocket", hint: "Space" },
    { word: "mermaid", hint: "Legend" },
    { word: "penguin", hint: "Bird" },
    { word: "sunflower", hint: "Flower" },
    { word: "zeppelin", hint: "Airship" },
    { word: "tornado", hint: "Twister" },
    { word: "skeleton", hint: "Bones" },
    { word: "mummy", hint: "Wrapped" },
    { word: "dragon", hint: "Myth" },
    { word: "rainbow", hint: "Colors" },
    { word: "dolphin", hint: "Mammal" },
    { word: "castle", hint: "Stone" },
    { word: "jigsaw", hint: "Puzzle" },
    { word: "airplane", hint: "Flight" },
    { word: "submarine", hint: "Underwater" },
    { word: "astronaut", hint: "Explorer" },
    { word: "jaguar", hint: "Cat" },
    { word: "whale", hint: "Mammal" },
    { word: "carousel", hint: "Ride" },
    { word: "glacier", hint: "Ice" },
    { word: "koala", hint: "Marsupial" },
    { word: "scorpion", hint: "Arachnid" },
    { word: "lightning", hint: "Electric" },
    { word: "sahara", hint: "Desert" },
    { word: "zeppelin", hint: "Airship" },
    { word: "avocado", hint: "Fruit" },
    { word: "beetle", hint: "Insect" },
    { word: "fireworks", hint: "Explosions" },
    { word: "bluejay", hint: "Bird" },
    { word: "glowworm", hint: "Light" },
    { word: "harp", hint: "Instrument" },
    { word: "waterfall", hint: "Cascade" },
    { word: "snowman", hint: "Winter" },
    { word: "zeppelin", hint: "Airship" },
    { word: "telescope", hint: "Stars" },
    { word: "mushroom", hint: "Fungi" },
    { word: "mermaid", hint: "Ocean" },
    { word: "parrot", hint: "Bird" },
    { word: "compass", hint: "Navigation" },
    { word: "crystal", hint: "Mineral" },
    { word: "tortoise", hint: "Slow" },
    { word: "astronomy", hint: "Space" },
    { word: "lighthouse", hint: "Light" },
    { word: "swordfish", hint: "Fish" },
    { word: "dragonfly", hint: "Insect" },
    { word: "snowstorm", hint: "Blizzard" },
    { word: "cactus", hint: "Plant" },
    { word: "algorithm", hint: "Problem-solving process" },
    { word: "data", hint: "Information" },
    { word: "binary", hint: "Base 2" },
    { word: "computer", hint: "Machine" },
    { word: "network", hint: "Connections" },
    { word: "programming", hint: "Coding" },
    { word: "database", hint: "Storage" },
    { word: "cloud", hint: "Online storage" },
    { word: "encryption", hint: "Data security" },
    { word: "machinelearning", hint: "Learning from data" },
    { word: "bigdata", hint: "Large datasets" },
    { word: "cybersecurity", hint: "Protecting systems" },
    { word: "firewall", hint: "Security barrier" },
    { word: "javascript", hint: "Programming language" },
    { word: "python", hint: "Programming language" },
    { word: "java", hint: "Programming language" },
    { word: "html", hint: "Web markup language" },
    { word: "css", hint: "Style sheets" },
    { word: "react", hint: "JavaScript library" },
    { word: "angular", hint: "Web framework" },
    { word: "nodejs", hint: "JavaScript runtime" },
    { word: "blockchain", hint: "Distributed ledger" },
    { word: "cryptocurrency", hint: "Digital currency" },
    { word: "IoT", hint: "Internet of Things" },
    { word: "debugging", hint: "Fixing errors" },
    { word: "versioncontrol", hint: "Tracking changes" },
    { word: "git", hint: "Version control system" },
    { word: "github", hint: "Code repository" },
    { word: "software", hint: "Programs" },
    { word: "hardware", hint: "Physical components" },
    { word: "heart", hint: "Symbol of love" },
    { word: "rose", hint: "Romantic flower" },
    { word: "kiss", hint: "Expression of affection" },
    { word: "date", hint: "Romantic meeting" },
    { word: "valentine", hint: "Holiday for love" },
    { word: "candlelight", hint: "Soft lighting" },
    { word: "passion", hint: "Strong emotion" },
    { word: "affection", hint: "Fondness" },
    { word: "couple", hint: "Two people in love" },
    { word: "wedding", hint: "Marriage ceremony" },
    { word: "engagement", hint: "Promise of marriage" },
    { word: "proposal", hint: "Asking for marriage" },
    { word: "flirt", hint: "Playful attraction" },
    { word: "adore", hint: "Deep affection" },
    { word: "romance", hint: "Loving connection" },
    { word: "sweetheart", hint: "Lover" },
    { word: "devotion", hint: "Loyalty" },
    { word: "soulmate", hint: "Perfect partner" },
    { word: "intimacy", hint: "Close connection" },
    { word: "together", hint: "Being with someone" },
    { word: "desire", hint: "Strong want" },
    { word: "hugs", hint: "Embrace" },
    { word: "kissed", hint: "Peck on the lips" },
    { word: "chocolate", hint: "Sweet treat, often gifted" },
    { word: "poetry", hint: "Romantic writing" },
    { word: "longing", hint: "Yearning" },
    { word: "true love", hint: "Deep affection" },
    { word: "butterflies", hint: "Feeling of excitement" },
    { word: "romantic", hint: "Expressing love" },
    { word: "rose", hint: "Classic romantic flower" },
    { word: "sunflower", hint: "Tall and bright flower" },
    { word: "rainlily", hint: "Weather plant" },
    { word: "lavender", hint: "Fragrant purple flower" },
    { word: "inception", hint: "Dreams within dreams" },
    { word: "avatar", hint: "Science fiction epic" },
    { word: "titanic", hint: "Ship disaster" },
    { word: "starwars", hint: "Space opera" },
    { word: "matrix", hint: "Reality vs simulation" },
    { word: "gladiator", hint: "Ancient Rome warrior" },
    { word: "batman", hint: "Superhero in Gotham" },
    { word: "harrypotter", hint: "Wizarding world" },
    { word: "gameofthrones", hint: "Fantasy drama" },
    { word: "strangerthings", hint: "Sci-fi thriller" },
    { word: "breakingbad", hint: "Chemistry teacher turned drug kingpin" },
    { word: "darkknight", hint: "Batman sequel" },
    { word: "friends", hint: "Sitcom about six friends" },
    { word: "theoffice", hint: "Workplace comedy" },
    { word: "spiderman", hint: "Superhero from Queens" },
    { word: "jurassicpark", hint: "Dinosaurs and adventure" },
    { word: "thegodfather", hint: "Mafia family saga" },
    { word: "thelionking", hint: "Animated African safari" },
    { word: "superman", hint: "Man of steel" },
    { word: "lordoftherings", hint: "Epic fantasy journey" },
    { word: "forrestgump", hint: "Man with a simple life" },
    { word: "ironman", hint: "Superhero with a high-tech suit" },
    { word: "wonderwoman", hint: "Superhero from Themyscira" },
    { word: "piratesofthecaribbean", hint: "Swashbuckling pirate adventures" },
    { word: "frozen", hint: "Disney animated movie" },
    { word: "darkknight", hint: "Batman vs Joker" },
    { word: "thewalkingdead", hint: "Zombie apocalypse" },
    { word: "sherlock", hint: "Detective stories" },
    { word: "themandalorian", hint: "Star Wars spinoff" },
    { word: "friends", hint: "Six friends in New York" },
    { word: "blackmirror", hint: "Technology gone wrong" },
    { word: "theoffice", hint: "Workplace comedy" },
    { word: "spiderman", hint: "Superhero from Queens" },
    { word: "jurassicpark", hint: "Dinosaurs and adventure" },
    { word: "thegodfather", hint: "Mafia family saga" },
    { word: "thelionking", hint: "Animated African safari" },

    
];
